app.json, environment.js, src/screens/Authentication.jsx
Si tu mets ton app a jour, ca fonctionne 🤩
juste pour plus de clareté, j'ai renomme staging en dev sinon on allait s'emmeler les pinceaux donc penses a renommer `env.staging.js` en `env.dev.js`
=> COM-1236 - fix relaease channel

App.js, app.json, src/api/users.js, src/components/ErrorMessage.jsx, src/components/NextEvent.jsx, src/components/form/Button.jsx, src/components/form/Input.jsx, src/context/AuthContext.js, src/screens/Authentication.jsx, src/screens/CourseList.jsx, src/screens/ForgotPassword.jsx, src/styles/screens.style.js, src/styles/variables.js
Ajout de la page pour recevoir le mail de mot de passe oublié
=> COM-1237 - add ofrgot password screen

src/screens/courses/CourseList.tsx
Filtrer créneaux avec étapes avant de de les regrouper par etape
SEUL le dernier commit compte
=> Com 1405 - FUSIONNER la 1423 avant puis rebase

src/components/IconButton.tsx, src/components/OnSiteHoursDisplay.tsx, src/components/modal/InfoModal.tsx, src/components/modal/OnSiteCellInfoModal.tsx, src/components/steps/OnSiteCell.tsx, src/core/helpers/utils.ts, src/styles/metrics.ts
- Cas d'usage : Ajout du design system a la modal d'info des etapes
=> Com 1382 design system

src/components/steps/ELearningCell.tsx
- Cas d'usage : Ajustement du design
=> COM-1414 - update design when opened

src/components/activities/ExitActivityModal.tsx, src/components/modal/CancelModal.tsx, src/components/steps/ELearningCell.tsx, src/components/style/Shadow.tsx, src/screens/courses/CardContainer.tsx, src/screens/courses/CourseProfile.tsx
Lorsque je suis sur une activité, j'ai un bouton pour quitter et revenir sur la liste des activités. De plus, le bouton de retour est géré sur android et à le même comportement que le bouton close. Enfin une modal vient me demander confirmation du close.
=> Com 1442 - Je peux quitter une activité

src/screens/courses/CardContainer.tsx, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/Transition.tsx
- Cas d'usage : on ne peut plus swiper sur les cartes +.marge ajoutée sur les cartes transitions
=> disable swipe for all cards + fix margin on transition template

src/components/activities/ExitActivityModal.tsx, src/components/cards/CardHeader.tsx, src/components/modal/InfoModal.tsx, src/components/steps/ELearningCell.tsx, src/components/steps/OnSiteCell.tsx, src/styles/metrics.ts
- Cas d'usage : changement de marge pour la modal de sortie d'activite + on peut cliquer sur un carre de 60px autour du bouton 'x' pour sortir de l'activite
=> COM-1442 fix margin + fix exit activity button

src/components/IconButton.tsx, src/components/cards/CardHeader.tsx, src/components/modal/InfoModal.tsx, src/components/steps/ELearningCell.tsx, src/components/steps/OnSiteCell.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard.tsx, src/styles/cards.ts, src/styles/metrics.ts
- Cas d'usage : On peut cliquer autour des iconbutton + fix marges sur page title texte media
=> COM-1433 add hitSlop on iconButton

src/screens/courses/cardTemplates/StartCard.tsx
marginHorizontal passé de PADDING.XXL à MARGIN.XL
=> Com 1470 fix: quick change on css 

.eslintrc.js, src/components/cards/CardHeader.tsx, src/screens/courses/CardContainer.tsx, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard.tsx, src/screens/courses/cardTemplates/Transition.tsx, src/store/actions.ts, src/store/reducers.ts, src/store/selectors.ts, src/types/StoreType.ts
- Cas d'usage : ajout de cardIndex et exitConfirmationModal dans le store 
Point de questionnement: Est-ce qu'on connecte le Footer et ExitModal ?
=> Com 1480 2

src/AppContainer.tsx, src/api/ressources/alenviAxios.ts, src/api/users.ts, src/context/AuthContext.ts, src/context/createDataContext.tsx
Ajout du refresh token -> si je quitte l'appli et que je la relance, j'obtiens un nouveau token d'authentification.
refacto : token to alenviToken + arriver sur la page mes formations lorsque je me connecte (https://reactnavigation.org/docs/bottom-tab-navigator/#props)
=> Com 1394 - RefreshToken

src/components/activities/ExitActivityModal.tsx, src/components/cards/CardHeader.tsx, src/screens/courses/CardContainer.tsx, src/screens/courses/cardTemplates/EndCard.tsx, src/screens/courses/cardTemplates/StartCard.tsx, src/store/actions.ts, src/store/reducers.ts, src/types/StoreType.ts
Reset des variables du store + lorsqu'on est sur la startCard et qu'on quitte l'activité, on quitte l'activite sans avoir a valider dans la modale
=> Com 1480 reset

src/components/ArrowButton.tsx, src/components/cards/CardFooter.tsx, src/components/cards/QuestionCardFooter.tsx, src/components/form/Button.tsx, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/EndCard.tsx, src/screens/courses/cardTemplates/SingleChoiceQuestionCard.tsx, src/screens/courses/cardTemplates/StartCard.tsx, src/styles/metrics.ts, src/types/CardType.tsx
correction du scroll sur start et end card, légère modification sur arrow button pour mettre les marges dans le footer plutôt que sur le bouton
design de qcu (boutons non fonctionnels mais possibilité de passer à la question suivante ou précédente
création du question card footer contenant un bouton continuer et une arrow back (composant réutilisable pour les tous les quiz)
=> Com 1434: 

src/api/activityHistories.ts, src/screens/courses/cardTemplates/EndCard.tsx, src/types/ActivityHistoryType.ts
Lorsque j'arrive sur la card de fin d'une activité, une ActivityHistory qui contient l'userId, l'activityId et la date de création
=> Com 1464 - ActivityHistory

src/components/cards/CardFooter.tsx, src/components/cards/QuestionCardFooter.tsx, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/TextMediaCard.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard.tsx, src/styles/cards.ts, src/types/CardType.tsx
créer carte TextMedia en se basant sur TitleTextMedia
=> COM-1501: create text media card

src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/TitleTextCard.tsx, src/types/CardType.tsx
Je peux voir les cartes TitleText.
Refacto de card type
=> Com 1502 - Add TitleText Card

src/screens/courses/cardTemplates/SingleChoiceQuestionCard.tsx, src/types/CardType.tsx
refacto falsy answer to qcuFalsyAnswer
=> Com 1505 - refacto falsyAnswer

src/components/cards/QuizProposition.tsx
Fix review de Romain, ajout d'un padding sur le marker
=> COM-1434 - Fix marker design

src/components/cards/QuestionCardFooter.tsx, src/screens/courses/cardTemplates/AnswerTextArea.tsx, src/screens/courses/cardTemplates/OpenQuestion.tsx
modification du style du placeholder (cf retour de Romain) et clavier disparait quand 2 open questions à la suite et qu'on switche entre les 2
=> COM-1507-2

src/components/cards/CardFooter.tsx, src/components/cards/QuestionCardFooter.tsx, src/screens/courses/cardTemplates/FlashCard.tsx
ajout de padding pour le texte
quand on switch entre deux flip card on revient à chaque fois sur le recto
=> COM-1503-2

src/api/activities.ts, src/api/activityHistories.ts, src/screens/courses/cardTemplates/EndCard.tsx, src/screens/courses/cardTemplates/StartCard.tsx, src/screens/courses/cardTemplates/SurveyCard.tsx, src/store/activities/actions.ts, src/store/activities/reducers.ts, src/types/store/ActivityStoreType.ts
Lorsque je reviens sur une activité finie, je retrouve mes réponses aux questionnaires (open question et sondage)
=> COM-1509 - get ActivityHistory on StartCard

src/components/cards/AnswerTextArea.tsx, src/components/cards/QuizProposition.tsx, src/screens/courses/cardTemplates/OpenQuestion.tsx
=> COM-1434: fix markdown

package-lock.json, src/components/cards/QuizProposition.tsx
- texte aligné au centre quelque soit la longueur de la ligne
=> COM-1434-margin: align text center

src/screens/courses/cardTemplates/OrderTheSequenceCard.tsx
si l'ordre est correct le score global à l'activité est incrémenté
=> COM-1521-save: increment score if good order

package-lock.json, package.json, src/components/ELearningCell/index.tsx, src/components/ELearningCell/styles.ts, src/components/ProgressPieChart/index.tsx, src/components/ProgressPieChart/styles.ts
camember de progression pour l'étape : 
- aucune activité faite : player icon rose
- une partie des activités faites : ring progress jaune
- la totalité des activités faites : check icon verte
=> COM-1523: design chart pie for step

src/AppContainer/index.tsx, src/components/ProgramCell/index.tsx, src/screens/courses/CourseList/index.tsx, src/screens/explore/About/index.tsx, src/screens/explore/About/styles.ts, src/screens/explore/Catalog/index.tsx, src/screens/explore/Catalog/styles.ts, src/styles/colors.ts, src/styles/fonts.js
depuis explore, lorsque je clique sur une étape, j'arrive sur une page à propos d'où je peux accéder au contenu de l'étape
=> Com 1526 : a propos

src/components/cards/CardFooter/index.tsx, src/components/cards/QuestionAnswerProposition/index.tsx, src/components/cards/QuestionAnswerProposition/styles.ts, src/core/data/constants.ts, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/FlashCard/index.tsx, src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx, src/screens/courses/cardTemplates/QuestionAnswerCard/styles.ts, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/TextMediaCard/index.tsx, src/screens/courses/cardTemplates/TitleTextCard/index.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx, src/screens/courses/cardTemplates/Transition/index.tsx, src/types/CardType.tsx
=> COM-1589: design question/answer

src/screens/courses/CourseList/index.tsx
changer "Prochains évènement" en "Mes prochains rendez-vous"
changer "Formations en cours" en "Mes formations en cours"
=> COM-1592: fix sections names

src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx, src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx, src/screens/courses/cardTemplates/SurveyCard/index.tsx, src/store/activities/actions.ts, src/store/activities/selectors.ts, src/types/store/ActivityStoreType.ts
- Cas d'usage :  je peux enregistrer mes réponses à questions/réponses + refacto de questionnaireAnswerList
=> Com 1589 redux

app.json, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/screens/courses/cardTemplates/FlashCard/index.tsx, src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/SurveyCard/index.tsx, src/screens/courses/cardTemplates/TextMediaCard/index.tsx, src/screens/courses/cardTemplates/TitleTextCard/index.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx, src/screens/courses/cardTemplates/Transition/index.tsx
Lorsque je reviens sur une carte de type quiz, je vois les reponses que j'avais entrees
=> COM-1457 wait until everything is loaded before displaying card

src/AppContainer/index.tsx, src/components/ELearningCell/index.tsx, src/screens/courses/CardContainer/index.tsx, src/screens/courses/CourseList/index.tsx, src/screens/courses/CourseProfile/index.tsx, src/screens/courses/SubProgramProfile/index.tsx, src/screens/courses/SubProgramProfile/styles.ts, src/screens/courses/cardTemplates/EndCard/index.tsx, src/screens/courses/cardTemplates/StartCard/index.tsx
scinder la logique de CourseProfile en 2 avec un SubProgramProfile. 
implique quelques changements sur d'autres composants.
=> COM-1598-refacto: refacto CourseProfile avec SubProgramProfile

src/api/programs.ts, src/screens/explore/About/index.tsx, src/screens/explore/Catalog/index.tsx
- Cas d'usage : lorsque j'appuie sur commencer/continuer j'arrive sur la prochaine activité à faire. Vu avec Romain: Si j'ai fini toutes les activites, j'arrive sur la page des etapes.)
=> Com 1615 refresh

src/screens/courses/CourseList/index.tsx, src/screens/courses/CourseList/styles.ts, src/screens/explore/Catalog/index.tsx, src/screens/explore/Catalog/styles.ts, src/styles/colors.ts, src/styles/common.ts
La valeur et la couleur du numéro qui s’affiche à côté de ‘mes formations à tester’ était celui de ‘mes formations en cours’
=> Com 1598 quickfix

src/components/cards/CardHeader/index.tsx, src/components/cards/ProgressBar/index.tsx, src/screens/courses/CardContainer/index.tsx, src/screens/courses/CourseProfile/index.tsx, src/screens/courses/CourseProfile/styles.ts, src/screens/courses/cardTemplates/EndCard/index.tsx, src/screens/courses/cardTemplates/StartCard/index.tsx, src/store/activities/selectors.ts, src/store/courses/actions.ts, src/store/courses/reducers.ts, src/store/courses/selectors.ts, src/types/store/CourseStoreType.ts
barre de formation qui nous indique notre avancée totale sur la formation.
=> COM-1601: ajout d'une barre de progression pour les formations

src/screens/explore/About/index.tsx
- Cas d'usage : on definit la variable isCourse lorsque l'on appuie sur le bouton continuer/commencer
=> COM-1615 use isCourse in about

src/components/CalendarIcon/index.tsx, src/components/ProgressPieChart/index.tsx, src/components/steps/OnSiteCell/index.tsx, src/screens/courses/CourseList/index.tsx, src/screens/courses/CourseProfile/index.tsx, src/types/StepType.tsx
- Cas d'usage : calcul de la progression dans le back et renvoi de cette dernière dans la formation
=> COM-1601-refacto: externalize progress calculate

src/components/ProgramCell/index.tsx, src/components/ProgramCell/styles.ts, src/components/steps/NextStepCell/index.tsx, src/screens/courses/CourseList/index.tsx
dans la page "mes formations" je peux voir ma progression pour une formation donnée
=> COM-1600: see progress for each course on course screen)

src/screens/explore/About/index.tsx
Reverts sophiemoustard/alenvi-mobile#155
=> Revert "COM-1615-navigation: focus on catalog when leave explore and come back"

src/components/ProgramCell/index.tsx, src/screens/courses/CourseList/index.tsx, src/screens/courses/CourseProfile/index.tsx, src/types/CourseType.tsx
Je vois les infos complementaires d'une formation sur la page mes formations et detail d;une formation
=> COM-1634 add misc next to programName

src/screens/profile/Profile/index.tsx
quand je ne suis pas connecté, le bouton déconnecté est quand même accessible
=> COM-1637-quickfix

src/styles/cards.ts
- Cas d'usage : ameliortion UI de l'arrfichage dess corrections
=> COM-1651 - remove text justify

src/components/cards/Video/index.tsx, src/components/cards/Video/styles.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard/styles.ts, src/types/CardType.tsx
- Cas d'usage : Video sur title text media
=> COM-1635 video on title text media

src/components/form/Input/styles.ts, src/screens/profile/ProfileEdition/index.tsx, src/screens/profile/ProfileEdition/styles.ts
=> COM-1638-quickfix: margin

src/AppContainer/index.tsx, src/api/users.ts, src/screens/profile/PasswordEdition/index.tsx, src/screens/profile/PasswordEdition/styles.ts, src/screens/profile/Profile/index.tsx, src/screens/profile/Profile/styles.ts
mettre à jour son mot de passe
=> COM-1642: update password

src/components/IconButton.tsx, src/components/cards/Audio/index.tsx, src/components/cards/Audio/styles.ts, src/core/data/constants.ts
On peut maintenant faire play et pause sur l'audio + debut d'un design plus proche de ce que l'on veut a la fin
=> Com 1636 design

src/AppContainer/index.tsx, src/components/form/Input/styles.ts, src/core/data/constants.ts, src/screens/profile/ProfileEdition/index.tsx, src/store/main/reducers.ts
flexibilité sur la fin des numéros de téléphone (si il y a un espace à la fin du numéro on n'indique pas d'erreur, la marge du shadow n'est pas coupée et les formations à tester apparaissent bien dans courselist après un updated du profil
=> COM-1638-feedback : apply Romain's feedbacks

src/types/CourseSlotType.tsx
- [] J'ai testé sur iphone
- Cas d'usage : Refacto courseId en course
=> COM-1647 - update course in courseSlot

package-lock.json, package.json, src/components/cards/Audio/index.tsx, src/components/cards/Audio/styles.ts, src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx
je peux lire un audio sur une carte titre media (et titre texte media)
=> Com 1636 progress

src/components/cards/Audio/index.tsx
- Cas d'usage : changement couleur de la petite boule sur le slider
=> COM-1636 set audio slider color to pink

app.json, environment.js
=> Upload to prod

src/screens/courses/CourseList/index.tsx, src/screens/courses/CourseList/styles.ts, src/screens/courses/CourseProfile/index.tsx, src/types/CourseType.tsx, src/types/SubProgramType.tsx
je peux voir les formations terminées
=> COM-1665: add achieved courses section

src/AppContainer/index.tsx, src/context/AuthContext.ts, src/screens/Authentication/index.tsx, src/screens/courses/CourseList/index.tsx, src/screens/explore/Catalog/index.tsx
- Cas d'usage : Quelques fix (des await manquant et des fix liés a l'authentification). Je ne pense pas que ca regle les problemes de connexion.
=> COM-1668 some fixes on tokens and resetReducers

src/AppContainer/index.tsx, src/components/CreateAccountForm/index.tsx, src/components/CreateAccountForm/styles.ts, src/components/form/Input/index.tsx, src/components/form/Input/styles.ts, src/screens/CreateAccount/index.tsx, src/screens/CreateAccount/styles.ts, src/screens/FirstConnection/index.tsx
si mon email n'est pas déjà connu je peux créer un compte (Prénom, Nom, Téléphone, Mot de passe) quand je valide je n'envoie rien pour l'instant j'ai juste un message qui m'indique que mon compte est créé
=> COM-1653: create account

src/api/users.ts, src/components/CreateAccountForm/index.tsx, src/context/AuthContext.ts, src/screens/CreateAccount/index.tsx
je peux enregistrer l'utilisateur nouvellement créé et son mot de passe
=> Com 1653 3

package-lock.json, package.json, src/core/helpers/asyncStorage.ts, src/screens/courses/cardTemplates/EndCard/index.tsx
- Cas d'usage : remplacement du paquet asyncStorage, verifier que la connexion/deconnexion se fait bien.
Je ne me suis pas occupé des tests jest parce que j'ai vu qu'ils etaient deja cassés et je me suis dit qu'il vallait peut etre mieux se pencher dessus dans un autre ticket. (conflit avec reactotron + probleme avec redux)
=> COM-1704 change deprecated asyncstorage

src/components/CreateAccountForm/index.tsx, src/components/CreateAccountForm/styles.ts, src/components/cards/AnswerTextArea/index.tsx, src/components/form/Input/index.tsx, src/screens/CreateAccount/index.tsx, src/screens/CreateAccount/styles.ts, src/screens/FirstConnection/index.tsx, src/screens/FirstConnection/styles.ts, src/screens/profile/PasswordEdition/index.tsx, src/screens/profile/ProfileEdition/index.tsx
quand je clique sur valider le champ dans firstconnection je passe directement à la page suivante (pas besoin de deux clics comme avant) + refacto de firstconnection et createaccountform dû à des problèmes d'affichages sur petits écrans (tester sur plusieurs tailles d'écran pour s'assurer que tous les cas sont couverts)
=> COM-1653: fix validation button

src/components/steps/NextStepCell/index.tsx, src/screens/courses/CourseList/index.tsx
Quand je clique sur un prochain rendez-vous j'accède à la formation rattachée
=> COM-1678: go to course when click on nextstepcell

src/components/cards/QuizCardFooter/index.tsx, src/components/cards/QuizCardFooter/styles.ts, src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/screens/courses/cardTemplates/FillTheGapCard/styles.ts, src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/styles.ts, src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/styles.ts, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/styles.ts, src/styles/cards.ts, src/types/CardType.tsx
Rajout d'un titre "Bonne réponse" ou "Mauvaise réponse" dans la correction des cartes quizz
=> COM-1679: add a title to explanation on quizz cards

src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/types/CardType.tsx
Maj du format des réponses dans les cartes Mettre dans l'ordre
TODO pour tester : 
- se mettre sur dev en webapp et api
- creer ses cartes mettre dans l'ordre et completer les reponses
- passer l'api en COM-1690
- aller sur la branche script COM-1690 et lancer mep40
- tester en mobile sur cette branche
=> COM-1690 - refacto OrderedAnswer

.eslintrc.js, package.json, src/api/users.ts, src/components/PictureModal/index.tsx, src/components/PictureModal/styles.ts, src/components/camera/Camera/index.tsx, src/components/camera/CameraPreview/index.tsx, src/screens/Camera/index.tsx, src/screens/profile/Profile/index.tsx, src/screens/profile/Profile/styles.ts, src/screens/profile/ProfileEdition/index.tsx, src/screens/profile/ProfileEdition/styles.ts, src/types/FormData.ts
je peux enregistrer ma photo ou la supprimer
=> Com 1695 2

src/components/cards/FillTheGapProposition/styles.ts, src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/types/CardType.tsx
Se mettre sur dev en API
Avoir lancé les scripts mep 40
tester les cartes Textes a trou
=> Refacto fill the gap

src/api/ressources/alenviAxios.ts, src/context/AuthContext.ts, src/core/helpers/alenvi.ts, src/core/helpers/asyncStorage.ts
- Cas d'usage : Je ne suis plus deconnecté regulierement (pour des indications pour tester voir pr back).
=> COM-1689 fix logout error

src/components/PictureModal/index.tsx, src/screens/profile/Profile/index.tsx, src/screens/profile/Profile/styles.ts
- Cas d'usage : On ne propose plus de telecharger l'image depuis la librairie. J'ai aussi ajoute les changements de style qu'avait fait Ulysse d'apres les retours de Romain
=> Com 1695 remove library

app.json
=> COM-1777 - in french

app.json
=> Build ios 1222

src/api/authentication.ts
- Cas d'usage : Je n'ai pas d'erreur lorsque je fais mot de passe oublié.
=> COM-1772 fix forgot password

src/components/CalendarIcon/index.tsx, src/components/ELearningCell/index.tsx, src/components/ProgramCell/index.tsx, src/components/ProgressPieChart/index.tsx
Homogénéiser les cercles de progression et utiliser ProgressPieChart partout
=> COM-1676: refacto progress pie chart

package-lock.json, package.json
mise à jour de axios : 0.19.2 => 0.21.1
=> COM-1724: updated axios

app.json
=> Update build number

app.json
- Cas d'usage : ajout des permissions android
=> add android permission

App.tsx, app.json, src/components/icons/FeatherButton/index.tsx, src/core/data/constants.ts, src/screens/courses/CourseProfile/index.tsx, src/screens/courses/CourseProfile/styles.ts, src/screens/courses/SubProgramProfile/index.tsx, src/screens/courses/SubProgramProfile/styles.ts
Ajout d'une ombre derriere la fleche de la fiche formation
MAJ de la modal de verification de mise a jour
=> Check update on focus

src/screens/profile/Profile/index.tsx, src/screens/profile/Profile/styles.ts
sur mon profil je peux voir le nombre de formations en cours et le nombre de formations terminées
=> COM-1766: add number of achieved courses on profile

src/components/cards/Audio/index.tsx
je peux écouter un audio en mode silencieux sur iOS (à tester sur ton iPhone @sophiemoustard, sur le simulateur on voit pas la différence)
+ quand un son se termine et que je reclique sur play, le son est rejoué (ce n'était pas le cas jusqu'alors)
=> Com 1767 2

App.tsx, src/api/version.ts
check si la version de l'app mobile est bien compatible (PR 1)
=> COM-1771: check update version

src/screens/Camera/index.tsx, src/screens/courses/CardContainer/index.tsx, src/screens/courses/CourseProfile/index.tsx, src/screens/courses/SubProgramProfile/index.tsx, src/screens/courses/cardTemplates/StartCard/index.tsx, src/screens/explore/About/index.tsx, src/screens/profile/PasswordEdition/index.tsx, src/screens/profile/ProfileEdition/index.tsx
quand je quitte une activité en plein milieu j'arrive sur courserProfile avec l'étape dépliée.
+ quand j'ai fini une activité et que je reviens sur courseProfile / subProgramProfile, je peux retourner sur courseList en faisant backhandler (android) (pour une raison étrange ce n'était pas possible)
=> Com 1761 2

app.json
=> Update build and version number

src/screens/courses/cardTemplates/EndCard/index.tsx
sur une carte à tester j'entends le bruit à la fin de l'activité
=> COM-1767: fix bug on draft e-learning

src/screens/explore/About/index.tsx, src/screens/explore/About/styles.ts
dans About ajout d'un titre "description" au dessus de la description et ajout des objectifs pédagogiques (contrairement à ce qui était écrit dans la strat technique, pas besoin de le rajouter au retour de route du back, il était déjà compris dedans)
=> COM-1805: add learning goals

app.json
- Cas d'usage : MEP pour la version 1.3.1
=> Update app name and version number

src/screens/courses/CourseProfile/styles.ts
- Cas d'usage : dans le bouton à propos l'icône et le texte ne sont pas alignés
=> COM-1806: align icon and text in about button

src/AppContainer/index.tsx, src/api/authentication.ts, src/api/users.ts, src/components/ForgotPasswordModal/index.tsx, src/components/ForgotPasswordModal/styles.ts, src/components/PasswordForm/index.tsx, src/components/PasswordForm/styles.ts, src/screens/EmailForm/index.tsx, src/screens/EmailForm/styles.ts, src/screens/PasswordReset/index.tsx, src/screens/profile/PasswordEdition/index.tsx, src/screens/profile/Profile/index.tsx, src/styles/fonts.js
lorsque j'ai oublié mon mot de passe je peux directement le récupérer depuis l'application grâce à un code envoyé par email
=> Com 1813 2

src/components/About/index.tsx, src/core/helpers/utils.ts, src/screens/explore/BlendedAbout/index.tsx, src/screens/explore/BlendedAbout/styles.ts
dans le "à propos" des formations mixtes j'ai accès à des informations complémentaires
(a une PR back associée)
=> COM-1808: add details on blended about

src/screens/explore/BlendedAbout/index.tsx, src/screens/explore/BlendedAbout/styles.ts
j'ai accès à l'application de téléphone / mail quand je clique dans la section contact
=> COM-1810: can click on phone and email

src/components/ForgotPasswordModal/index.tsx
- Cas d'usage : correction de bug pour saisir le code de validation et message d'erreur ne change pas si l'erreur est toujours la même
(cf. commentaire de Romain)
=> COM-1814: fix code

src/components/ForgotPasswordModal/index.tsx
- Cas d'usage : je peux effacer le code recu par sms ou mail quand j'ai fini de l'ecrire ou non
=> COM-1814 - fix back press

src/screens/explore/BlendedAbout/index.tsx, src/screens/explore/BlendedAbout/styles.ts
icones devant numéro de téléphone et mail dans contact
=> COM-1810: add icons for contact

src/components/cards/OrderProposition/index.tsx, src/components/cards/OrderProposition/styles.ts
Ajout d'une icone pour inciter au drag sur les cartes orderthesequence. Cf figma (c'est pas la même icone mais c'est validé par Romain)
=> COM-1863 - Fix design

src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/types/CardType.tsx
- Cas d'usage : si les reponses sont interchangeable c'est pris en compte
=> COM-1847 can switch answers on fill the gap card

src/components/cards/OrderProposition/index.tsx
Le dragButton change de couleur lors de la validation d'une carte OrderTheSequence
=> COM-1863 - Change dragButton color when validated

src/screens/courses/CardContainer/index.tsx, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/screens/courses/cardTemplates/FlashCard/index.tsx, src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/SurveyCard/index.tsx, src/screens/courses/cardTemplates/TextMediaCard/index.tsx, src/screens/courses/cardTemplates/TitleTextCard/index.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx, src/screens/courses/cardTemplates/Transition/index.tsx
La solution proposée dans le ticket (que j'ai dev dans cette PR)  me pose 2 soucis :
- elle soulève l'erreur suivante : 'Cannot update a component from inside the function body of a different component'
- c'est une mauvaise pratique de donner à l'enfant un moyen de modifier le composant parent (ce qui est probablement lié à l'erreur au dessus).
J'ai essayé une autre méthode : passer une props 'userSwipedRight' à l'enfant, comme ça l'enfant gère, lorsque l'user à swipe à droite, s'il peut changer d'écran ou pas. Je me suis rapidement heurté face au problème de la remise à false de ce boolean (il faut le remettre à false dès que l'enfant à traité cette info. Si l'utilisateur avait le droit de swipe -> on passe à la carte suivante et on remet le boolean userSwipedRight à false. Sinon on le …
=> Com 1790 - Swipe

src/core/data/constants.ts, src/screens/courses/CardContainer/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
master en api) - j'ai testé sur dev car "l'ancienne version de l'api" n'est pas encore deployé sur master
- Oui parce que les changements ne dependent pas d'une reponse de l'api
- Non parce que -np 
- Cas d'usage : swipe moins sensible - la valeur exacte est en validation par Romain
doc utilisé: https://docs.swmansion.com/react-native-gesture-handler/docs/api/gesture-handlers/pan-gh/
=> COM-1790 swipe sensibility

src/AppContainer/index.tsx
master en api)
- Oui parce que je n'ai pas changé l'api, ni changé l'utilisation de l'api du mobile
- Cas d'usage : Sur iphone: je ne peux plus partir d'une activité en swipant vers la gauche. On ne peut pas partir de l'activite des l'arrivée sur le startCard, est-ce genant ?
=> COM-1913 cant dismiss cardContainer

src/components/ZoomImage/index.tsx, src/components/ZoomImage/styles.ts, src/screens/courses/CardContainer/index.tsx, src/screens/courses/cardTemplates/CardTemplate.tsx, src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/screens/courses/cardTemplates/FlashCard/index.tsx, src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/screens/courses/cardTemplates/QuestionAnswerCard/index.tsx, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/SurveyCard/index.tsx, src/screens/courses/cardTemplates/TextMediaCard/index.tsx, src/screens/courses/cardTemplates/TitleTextCard/index.tsx, src/screens/courses/cardTemplates/TitleTextMediaCard/index.tsx, src/screens/courses/cardTemplates/Transition/index.tsx
master en api)
- Oui parce que je ne touche pas au appel a l'api
- ~~Non parce que~~
Dans titletextmedia et textmedia seulement pour l'instant, quand je clique sur une image je peux zoomer dessus.
Quand on zoom l'image, le swipe est bloqué des 2 cotés
=> Com 1861 zoom

src/components/CreateAccountForm/index.tsx, src/components/CreateAccountForm/styles.ts, src/core/data/rules.ts
master en api)
- Oui parce que on touche à aucune data
déplacement de la phrase pour ouvrir la modal de CGU en dessous du bouton valider
=> COM-1899: modal text at page bottom

src/components/CreateAccountForm/index.tsx, src/components/CreateAccountForm/styles.ts, src/screens/EmailForm/index.tsx, src/screens/EmailForm/styles.ts, src/styles/accountCreation.ts
master en api)
- Oui parce que je n'ai changé que du style
- Cas d'usage : le bouton est a la meme position entre EmailForm et CreateAccountForm
=> Com 1899 button

app.json
master en api)
- Oui parce que je n'ai change que app.json
- Cas d'usage : changement version pour mep
=> change version and build number

src/components/CreateAccountForm/index.tsx, src/components/form/Input/index.tsx, src/screens/CreateAccount/index.tsx
master en api)
- Oui parce que je touche pas au back ou aux datas 
- Cas d'usage : quand je créée mon compte sur l'app, je sais que le n° de téléphone et le prénom sont optionnels
=> COM-1896: add optional on field

.gitignore, App.tsx, app.json, package-lock.json, package.json
master en api)
- Oui parce qu'il n'y a pas d'interaction avec l'api
- Cas d'usage : Lien avec firebase.
Pour pouvoir tester: ajouter les deux fichiers que Sophie a  envoye par dashlane a la racine + ajouter la partie "web" dans la app.json ⚠️ a ne pas push sur git.
Ouvrez l'app, connectez vous a firebase, dans le dashboard il y a une partie "Nombre d'utilisateurs au cours des 30 dernieres minutes" et vous devriez voir votre connexion.
Note: Pour l'instant il n'y a aucune info remontée a firebase. Le prochain ticket permettra d'avoir les differents ecrans ou on navigue ce qui permettra d'avoir des infos plus interessantes. L'evenement que j'ai mis n'est …
=> COM-1838 first draft for firebase

app.json
master en api)
- Oui parce que uniqumeent modification du app.json
- Cas d'usage :  suppression d'une cle duplique dans le app.json
=> COM-1964 remove duplicate key in app.json

src/AppContainer/index.tsx, src/AppContainer/styles.ts, src/Home/index.tsx, src/Home/styles.ts, src/core/helpers/analytics.ts
master en api)
- Oui parce qu'il n'y a pas d'interactino avec l'api 
- Cas d'usage : Affichage des ecrans visités sur google analytics. Pour l'instant on n'a pas le type des cartes. 
Pour verifier si firebase dans le menu: selectionnez realtime, cochez evenements et non utilisateurs, et dans tendance vous avez le details. 
Rappel: pensez a mettre la config web :)
=> COM-1839 log eventwhen changing screen

App.tsx, src/api/version.ts, src/core/data/constants.ts
master en api)
- Non parce que j'ai ajoute un nouveau parametre dans la route
- Si j'en envoie un nouveau, explication et gestion de la compatibilite: envoie du parametre pour que la route fonctionne pour formation et erp. Normalement l'api sera en prod lorsque l'on mettra l'app a jour. 
- Cas d'usage : La modale de mise a jour doit s'afficher si besoin.
=> Change check version

src/core/helpers/analytics.ts
master en api)
- Cas d'usage : Mise en place de firebase
=> COM-1839 - additional info for engagement

src/AppContainer/index.tsx, src/api/questionnaires.ts, src/components/questionnaires/QuestionnaireCell/index.tsx, src/components/questionnaires/QuestionnairesContainer/index.tsx, src/screens/courses/ActivityCardContainer/index.tsx, src/screens/courses/CourseProfile/index.tsx, src/screens/courses/QuestionnaireCardContainer/index.tsx, src/screens/courses/cardTemplates/ActivityEndCard/index.tsx, src/screens/courses/cardTemplates/QuestionnaireEndCard/index.tsx, src/styles/endCard.ts
master en api)
- Non parce que j'utilise une route créé dans COM-1995
- Cas d'usage :  je peux répondre à un questionnaire
=> COM-1996: can read a questionnaire

src/components/questionnaires/QuestionnairesContainer/index.tsx, src/components/questionnaires/QuestionnairesContainer/styles.ts
master en api) -np
- ~~[ ] Je l'ai ajouté dans env.dev et env.prod aussi~~
Correction des retours de Romain :
- Ajout d'un séparateur -> ajout de borderBottom
- Texte en gras, la font ne charge pas sous android, le problème vient de la balise text dans une autre balise text : 
- https://github.com/facebook/react-native/issues/19757
- https://stackoverflow.com/questions/44257982/react-native-nested-text-with-differnt-fontsizes-initial-first-letter …
=> COM-1995 - Fix Romain's review

src/components/questionnaires/QuestionnaireCell/index.tsx, src/screens/courses/QuestionnaireCardContainer/index.tsx, src/types/QuestionnaireType.ts
master en api)
- Non parce que nouvelles routes mais MEP intermédiaire
- ~~[] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas~~
- Cas d'usage : dans le modèle Questionnaire, le champ title est renommé name
=> COM-2027: change title in name

src/api/questionnaireHistories.ts, src/screens/courses/QuestionnaireCardContainer/index.tsx, src/screens/courses/cardTemplates/ActivityEndCard/index.tsx, src/screens/courses/cardTemplates/QuestionnaireEndCard/index.tsx
master en api)
- Non parce que je créé une nouvelle route et que je reçoit une 404 si elle n'existe pas en back
- Cas d'usage : quand je réponds a un questionnaire de pré formation, mes réponses sont enregistrée (je ne peux répondre qu'une seule fois)
=> COM-2014: can save questionnaire history

app.json
master en api)
- Oui parce que changement d version uniquement --> ajout dans le slite mep
- Cas d'usage : changement version pour mep
=> change versions

src/components/CoursesSection/styles.ts, src/components/questionnaires/QuestionnairesContainer/index.tsx, src/types/QuestionnaireType.ts
master en api)
- Oui parce que on n'appelle pas de nouvelle route
- Cas d'usage :  je vois le questionnaire de fin de formation
=> COM-2037: display end of course questionnaire

src/components/About/index.tsx, src/components/CreateAccountForm/index.tsx, src/components/ELearningCell/index.tsx, src/components/steps/OnSiteCell/index.tsx, src/components/steps/OnSiteCellInfoModal/index.tsx, src/components/steps/OnSiteInfoItem/index.tsx, src/screens/CreateAccount/index.tsx, src/screens/courses/CourseProfile/index.tsx
master en api)
Je vous propose ces modifications / refontes pour ameliorer quelques composants notamment avec l'utilisation de `useCallback`, mieux utiliser `useState` pour gerer les variables d'etat, ...
=> Clean code and callback

app.json
=> test-notifications: update version

app.json
master en api)
- Oui parce que changement de la version uniquement --> il faudra modifier les versions dispo sur dev
- Cas d'usage : changement versions
Je ne suis pas encore passe a la v2 pour que quand on sorte la nouvelle app mardi ce soit la v2.0.0 et non la v2.0.1
=> change version for internal tests

src/components/CreateAccountForm/index.tsx, src/screens/EmailForm/index.tsx, src/styles/accountCreation.ts
master en api)
- Oui parce que je ne modifie pas les appels au back
- ~~[ ] Je n'ai pas changé de constante~~
- Cas d'usage : Sur le formulaire de première connexion si on passe à la page suivante (exemple de prénom à nom) directement en cliquant sur valider sans fermer le clavier je n'ai plus le bug avec la grosse margin au-dessus du clavier
TEST : sur iPhone et Android : passer plusieurs fois entre les différentes pages du formulaire de première connexion en fermant/sans fermer …
=> COM-2113: fix bug with keyboard when switch screen

__tests__/authentication.test.js, package-lock.json, package.json
master en api)
- Cas d'usage : fix du test authentication.tests. Commentaires sur jira
+ Fix d'un bug : qs est utilisé dans l'app mais n'a jamais été dans le package.json. Avec un rm package-lock && npm i, on se retrouve sans qs. Ce qui fait bugger axios, donc toute l'app. Je l'ai rajouté dans le package.json du coup
=> COM-1880 downgrade react-test-render

__tests__/authentication.test.js, src/AppContainer/index.tsx, src/api/authentication.ts, src/api/axios/notLogged.ts, src/api/users.ts, src/api/version.ts, src/components/MaintenanceModal/index.tsx, src/components/MaintenanceModal/styles.ts, src/screens/PasswordReset/index.tsx, src/screens/profile/PasswordEdition/index.tsx
master en api)
- Oui parce qu'on ne touche pas au back
-~~ [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas~~
- Cas d'usage : lorsque je coupe le back la modale de maintenance s'affiche (en étant connecté ou non)
=> COM-2254: add 502,503 interceptor

src/components/PasswordForm/index.tsx, src/screens/EmailForm/index.tsx, src/screens/courses/CardScreen/index.tsx, src/screens/explore/BlendedAbout/index.tsx, src/screens/profile/ProfileEdition/index.tsx
master en api)
- Oui parce que je modifie juste du texte
- Cas d'usage : formes inclusives sur : 
- les modales lorsqu'on quitte une activité, l'édition du mot de passe/du profil, la première connexion
- le message d'erreur lorsqu'on change son mail pour un mail préexistant (profile edition)
- à propos des formations mixtes : intervenant => intervenant(e)
=> COM-2109: inclusive forms

src/AppContainer/index.tsx, src/components/PasswordForm/index.tsx, src/screens/CreateAccount/index.tsx, src/screens/courses/ActivityCardContainer/index.tsx, src/screens/courses/CourseList/index.tsx, src/screens/courses/CourseProfile/index.tsx, src/screens/courses/QuestionnaireCardContainer/index.tsx, src/screens/courses/SubProgramProfile/index.tsx, src/screens/explore/Catalog/index.tsx, src/screens/explore/ELearningAbout/index.tsx, src/screens/profile/Profile/index.tsx, src/screens/profile/ProfileEdition/index.tsx
master en api)
- Oui parce que je ne touche pas aux routes
-~~ [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas~~
- Cas d'usage : avec les interceptors on renvoit error et non error.response, hors les statusCode en cas d'erreurs sont lu via e.status => il faut les changer en e.response.status
=> COM-2109: fix error status

src/screens/profile/Profile/index.tsx, src/screens/profile/Profile/styles.ts
master en api)
- Oui parce que juste un changement visuel
- Cas d'usage : sur Android quand on fait une demande de rattachement à une structure le nom de la structure est en gras (il ne l'était pas avant)
=> COM-2306: fix bold company name

app.json
=> MAJ version for mep

app.json
=> MEP 29/09 - build number

src/components/CalendarIcon/index.tsx, src/core/helpers/dates.ts, src/screens/explore/BlendedAbout/index.tsx
master en api)
- Oui parce que traitement front uniquement
-~~ [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.~~
- [ x Je n'ai pas changé de constante
-~~ J'ai ajouté une variable d'environnement :~~
- Cas d'usage : MEP à la volée du bug de jour
=> Fix bug relase

src/context/AuthContext.ts, src/core/data/constants.ts
master en api)
- Cas d'usage : ajout de constante pour les differentes actions de redux
=> COM-2199 add constant in context

src/components/ForgotPasswordModal/index.tsx, src/components/PasswordForm/index.tsx, src/reducers/error.tsx, src/screens/EmailForm/index.tsx, src/screens/profile/ProfileEdition/index.tsx
master en api)
- Cas d'usage : remplacement des `useState` par des `useReducer` pour gerer les message d'erreurs
=> COM-2200 create reducer for error management

src/screens/EmailForm/index.tsx, src/screens/explore/BlendedAbout/index.tsx, src/types/CourseTypes.tsx
master en api)
- ⚠️ Non parce que: le champ Contact a été modifié. Cela dit, si on utilise une veille version, rien ne plante. On a juste la section contact qui ne s'affiche plus dans la page "a propos" d'une formation mixte
Pas de changements fonctionnels dans cette PR, on veut simplement afficher la section contact dans la page "à propos" d'une formation mixte.
=> COM-2556 refacto contact section in course info

app.json
=> mep 14-12 build version

.github/pull_request_template.md
---
---
- Périmètre interfaces / rôles :
- Cas d'usage :
=> COM-2599 chamge checklist

app.json
=> mep-04-02: build version

app.json
=> mep-18-03: build version

app.json, src/core/helpers/utils.ts
MEP a la volée pour fix le bug de l'audio
=> MEP a la volée 28/03

app.json
=> mep-01-04: build versions

src/screens/Authentication/index.tsx, src/screens/profile/ProfileEdition/index.tsx
---
---
- Périmètre interfaces / rôles : formation / tous
- Cas d'usage : quand je rentre un espace en trop dans mon mail à l'authentification celui-ci n'est pas pris en compte
- Comment tester ? : se connecter en rentrant un espace en trop dans son mail
=> COM-2786: add trim to authenticate

src/components/DeletionConfirmationModal/index.tsx
---
---
- Périmètre interfaces / rôles : mobile-formation - norolenocompany
- Cas d'usage : je peux supprimer mon compte si je n'ai pas de structure et que je n'ai pas fait d'activité
- se connecter avec en compte sans structure
- s'inscrire à une formation elearning => je peux supprimer mon compte
- s'inscrire à une formation elearning et faire une activité => je ne peux pas supprimer mon compte 
=> COM-2819: show error message

app.json
=> mep-02-06: build versions

src/components/DeletionConfirmationModal/index.tsx
---
---
- Périmètre interfaces / rôles : mobile-formation / sans structure
- Cas d'usage : je peux supprimer mon compte même en ayant fait des activités elearning
- créer un compte
- le supprimer directement => il est supprimé de la BDD
- créer un compte et faire des activités
- le supprimer => il est anonymisé en BDD
- refaire les deux cas précédents mais killer l'app juste après avoir valider la suppression (ne pas cliquer sur OK sur la modale de confirmation) => quand je reviens sur l'app je suis sur la page d'authentication 
=> COM-2820: fix disconnection

app.json
=> mep-01-07: build versions

app.json, src/components/DeletionConfirmationModal/index.tsx, src/screens/courses/CourseProfile/index.tsx
=> MEP 01/07/2022

src/components/ZoomImage/index.tsx, src/components/ZoomImage/styles.ts
---
---
- Périmètre interfaces / rôles : ETQ apprenant 
- Cas d'usage :  Le header est lisible
- Lancer une activité contenant des medias et verifier que le zoom fonctionne + que le header s'affiche correctement lorsque l'image est zoomée
=> COM-2924 - fix display on zoomImage

app.config.js, environment.ts, src/core/data/constants.ts
---
---
- Périmètre interfaces / rôles : Toute
- Cas d'usage : Je peux publier l'application sans avoir a changer mes variables d'environnement
Changer son fichier .env
Lancer l'application en local -> elle est branchée sur le back local
Publier l'application en dev et la tester -> elle est branchée sur le back dev
pour info je suis revenue en arrière que la constante APP_VERSION car c'est un changement que j'avais oublié d'enlever dans la PR d'avant
=> Com 2965 expo publish

.github/pull_request_template.md
ajout du test sur tablette dans les tests de PR
=> COM-2973: add tablet test on github

app.config.js
---
---
- Périmètre interfaces / rôles : Tous
- Cas d'usage :
Cette PR fait suite a la PR https://github.com/sophiemoustard/compani-formation/pull/482. J'avais enlevé la configuration sentry du fichier `app.json` (maintenant `app.config.json`) qui n'est pas utile pour `eas build` mais ca l'esy pour `expo build` je l'ai donc remis
idem la distinction pour le nom de l'application est nécessaire pour `eas` car on peut faire des build de test directement installable sur le téléphone mais ca bloque pour `expo build` je suis donc revenue en arrière
- Comment tester ?
Pour ios : 
Le bug remonté dans sentry est ici : https://sentry.io/organizations/alenvi/issues/3554431497/?alert_rule_id=4037289&alert_timestamp=1662112438389&alert_type=email&environment=production&project=5606219&referrer=alert_em …
=> Com 2965 app config

.gitignore, package-lock.json, package.json
---
---
- Périmètre interfaces / rôles : Tout
- Cas d'usage : Suppression de l'outil reactotron qu'on utilise pas
Lancer `npm ci`
Tester l'application -> elle doit bien fonctionner
=> COM-2965 - remove reactotron

src/screens/courses/list/styles.ts, src/screens/explore/Catalog/styles.ts
---
---
- Périmètre interfaces / rôles : mobile-formation / tous
- Cas d'usage : les tâches en arrières plan s'affichent correctement sur tablette
- Comment tester ? : afficher la section "mes formations" et "explorer" sur tablette
=> COM-2986: use percentages

src/components/steps/NextStepCell/index.tsx, src/components/steps/StepCellTitle/index.tsx, src/components/steps/StepCellTitle/styles.ts, src/screens/courses/list/helper.ts, src/types/StepTypes.tsx
---
---
- Périmètre interfaces / rôles : onglet intervenant
- Cas d'usage :
- ajout des infos complementaires d'une formation sur les icones de la section "mes prochains rdv" 
- tester sans misc
- tester avec un misc classique (genre "groupe 5")
- tester avec un misc plus long 
=> COM-2975-3 add misc to next step

src/api/courses.ts, src/screens/courses/list/LearnerCourses/index.tsx, src/screens/profile/Profile/index.tsx, src/types/AxiosTypes.ts
---
---
- Périmètre interfaces / rôles : mobile formation tous
- Cas d'usage : je peux afficher la liste de mes formations (apprenant) et voir le nombre de formations suivies sur le profil
- afficher la liste des formations (apprenant)
- afficher le nombre de formations suivies sur le profil 
=> COM-2994: replace route

app.config.js, src/navigation/Home/index.tsx
- build version mep 30/09
- blocage de l'accès à l'onglet formateur
=> mep-30-09: prepare mep

app.config.js, eas.json, environment.ts, package-lock.json, package.json, src/App/index.tsx, src/AppContainer/index.tsx
---
---
- Périmètre interfaces / rôles : Tous
- Cas d'usage : Deploiement et publication de l'application en distribution interne et production
- Comment tester ? : Tout est détaillé [ici](https://www.notion.so/Test-eas-build-expo-publish-5c2c6fc43b3c4b3188d608a5b7396d0f)
=> COM-3210 - update eas build to allow expo publish

app.config.js
=> mep-14-10: prepare mep

src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/AdminCourseProfile/styles.ts
=> COM-3261: fix bugs

src/components/ELearningCell/index.tsx, src/components/ProgramCell/index.tsx, src/components/ProgramCell/styles.ts, src/components/steps/StepCellTitle/index.tsx, src/core/helpers/dates/companiDurations.ts, src/core/helpers/utils.ts, src/screens/courses/list/LearnerCourses/index.tsx, src/screens/courses/list/TrainerCourses/index.tsx, src/screens/courses/list/helper.ts, src/screens/explore/Catalog/index.tsx, src/types/StepTypes.tsx
---
NB : possibilité d'amélioration : avoir comme type une durée ISO plutot qu'un string. En cherchant un peu j'ai l'impression qu'il n'y a rien de prévu facile pour ce cas la, du coup je me suis dit que ca sortait un peu du scope et que ca risquait de prendre trop de temps. 
=> COM-3249 refacto theoreticalHours

src/components/CalendarIcon/index.tsx, src/components/steps/LiveCellInfoModal/index.tsx, src/components/steps/LiveHoursDisplay/index.tsx, src/components/steps/LiveInfoItem/index.tsx, src/core/data/constants.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/explore/BlendedAbout/index.tsx
=> COM-3254 use constants with .format( fct

app.config.js, eas.json
=> mep-10-11: prepare mep

src/components/CalendarIcon/index.tsx, src/core/helpers/asyncStorage.ts, src/core/helpers/dates/companiDates.ts, src/screens/courses/list/helper.ts
=> COM-3276 sync companiDate mths with api

eas.json
change release-channel version
=> fix releaseChannel version

package.json
=> COM-3338 - remove preinstall commmand

eas.json, package.json
=> MES 6/02/2023

app.config.js
=> COM-3428 remove files from app.config.js

.gitignore, package.json
=> COM-3428 config firebase for notifications

src/types/CourseTypes.tsx
=> COM-3535: rename variable

package.json, yarn.lock
=> Remove sharp-cli

app.config.js, eas.json
=> update-version-2-20-0-3: update version to 2.20.0

src/AppContainer/index.tsx, src/api/users.ts, src/screens/courses/profile/LearnerCourseProfile/index.tsx
=> Mep onair 1710

src/core/data/constants.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/types/AttendanceSheetTypes.ts
=> COM-3585: can upload intra_holding attendance sheet

app.config.js, eas.json
=> update-version-2-22-0: update version to 2.22.0

src/api/courses.ts
=> COM-3611 - add format in query

src/api/authentication.ts, src/components/ForgotPasswordModal/index.tsx, src/components/PersonCell/index.tsx, src/context/AuthContext.ts, src/core/data/constants.ts, src/screens/Authentication/index.tsx, src/screens/CreateAccount/index.tsx, src/screens/LoginCodeForm/index.tsx, src/screens/PasswordReset/index.tsx, src/types/AuthenticationTypes.ts, src/types/CourseTypes.tsx, src/types/NavigationType.ts, src/types/UserType.ts
=> COM-3635 - define firstMobileConnectionMode when user registers

src/screens/courses/profile/LearnerCourseProfile/index.tsx, src/screens/courses/profile/TrainerCourseProfile/index.tsx, src/screens/courses/profile/helper.tsx
=> COM-3649 - remove warning on courseprofile scrollview

app.config.js
=> COM-3643: fix pro guard rules

app.config.js, eas.json
=> update-version-2-23-0: update version to 2.23.0

app.config.js
=> remove useless spaces + add comma

app.config.js, eas.json
=> update version to 2.24.0

jest.setup.js, src/components/ZoomImage/index.tsx, src/screens/courses/profile/AdminCourseProfile/index.tsx
=> COM-3667: use react-native-gesture-handler API 2 for zoom

src/screens/courses/cardTemplates/SurveyCard/index.tsx, src/types/CardType.tsx
=> COM-3668 - change labels in Survey card

src/screens/courses/cardTemplates/SurveyCard/index.tsx, src/screens/courses/cardTemplates/SurveyCard/styles.ts, src/types/CardType.tsx
=> COM-3675 : display tooltip

src/core/data/constants.ts, src/types/QuestionnaireType.ts
=> COM-3678 : add questionnaire type

app.config.js, eas.json
update version to 2.26.0 / 200
=> update version to 2.26.0 / 200

app.config.js, babel.config.js, package.json, yarn.lock
=> COM-3540: allow access to app on web browser

src/AppContainer/index.tsx
=> COM-3713: block notifications on web

src/navigation/Home/index.tsx, src/screens/profile/Profile/index.tsx
=> COM-3714: block sections where camera is accessible

src/components/cards/Video/index.tsx, src/components/cards/Video/styles.tsx
=> COM-3731: fix video player

src/AppContainer/index.tsx, src/components/ToastMessage/index.tsx, src/components/ToastMessage/styles.ts
=> COM-3729 : popup

src/components/cards/Audio/index.tsx, src/components/cards/Audio/styles.ts
=> COM-3732: specific player for web

src/components/cards/Audio/index.tsx
=> COM-3732: can replay audio on web

app.config.js, eas.json
=> update version 2.28.0

src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
=> COM-3738: fix fill the gap card for web

src/AppContainer/index.tsx, src/components/About/index.tsx, src/components/CoursesSection/index.tsx, src/components/CreateAccountForm/index.tsx, src/components/ImagePreview/index.tsx, src/components/InternalRulesModal/index.tsx, src/components/Modal/index.tsx, src/components/PasswordForm/index.tsx, src/components/UpdateAppModal/index.tsx, src/components/camera/Camera/index.tsx, src/components/cards/Audio/index.tsx, src/components/cards/Video/index.tsx, src/components/steps/StepCellTitle/index.tsx, src/core/data/constants.ts, src/core/data/tabs.ts, src/navigation/AppNavigation/index.tsx, src/navigation/Home/index.tsx, src/screens/Authentication/index.tsx, src/screens/CreateAccount/index.tsx, src/screens/EmailForm/index.tsx, src/screens/LoginCodeForm/index.tsx, src/screens/courses/ActivityCardContainer/index.tsx, src/screens/courses/QuestionnaireCardContainer/index.tsx, src/screens/courses/cardTemplates/OpenQuestionCard/index.tsx, src/screens/courses/list/LearnerCourses/index.tsx, src/screens/courses/profile/LearnerCourseProfile/index.tsx, src/screens/explore/Catalog/index.tsx, src/screens/profile/Profile/index.tsx, src/screens/profile/ProfileEdition/index.tsx
=> COM-3739: display tab names

src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/store/cards/hooks.ts, src/store/cards/selectors.ts, src/store/cards/slice.ts, src/types/ActivityTypes.tsx
=> COM-3757: can store qcm answers

src/screens/courses/cardTemplates/ActivityEndCard/index.tsx, src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/store/cards/hooks.ts, src/store/cards/selectors.ts, src/types/ActivityTypes.tsx, src/types/CardType.tsx
=> COM-3758: can send quizz answers list to database

src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/types/ActivityTypes.tsx, src/types/CardType.tsx
=> COM-3759 : refacto qcu

src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/store/cards/selectors.ts
=> COM-3771: save qcu answers in store

src/screens/courses/cardTemplates/ActivityEndCard/index.tsx, src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx, src/store/cards/hooks.ts, src/store/cards/selectors.ts, src/types/ActivityTypes.tsx, src/types/CardType.tsx
=> COM-3773: can add order the sequence answers in bdd

src/screens/courses/CardScreen/index.tsx
=> COM-3791: fix pan gesture offset

app.config.js, eas.json
=> update version 2.29.0

src/components/cards/FillTheGapProposition/index.tsx, src/components/cards/FillTheGapPropositionList/index.tsx, src/components/cards/FillTheGapQuestion/index.tsx, src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/types/CardType.tsx
=> COM-3778: can answer fill the gap card

src/screens/Authentication/index.tsx, src/screens/Authentication/styles.ts
=> COM-3793: responsive authentication page

src/screens/courses/CardScreen/index.tsx
=> MEP intermédiaire OTA

src/components/CourseProfileHeader/index.tsx, src/components/CourseProfileHeader/styles.ts
=> COM-3803: header full width on web

src/screens/courses/cardTemplates/ActivityEndCard/index.tsx
=> COM-3775: fix bug order in fill the gap

src/components/ForgotPasswordModal/styles.ts, src/screens/LoginCodeForm/styles.ts
=> COM-3800: fix code size

src/screens/profile/Profile/styles.ts
=> COM-3804: center background shape

src/components/cards/OrderProposition/index.tsx, src/screens/courses/cardTemplates/CardTemplate/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/screens/courses/cardTemplates/OrderTheSequenceCard/styles.ts
=> Com 3792 2

src/screens/courses/QuestionnaireCardContainer/index.tsx
=> COM-3821: pass number to boolean

src/screens/courses/cardTemplates/SurveyCard/index.tsx, src/screens/courses/cardTemplates/SurveyCard/styles.ts
=> COM-3839: scrollable survey

src/components/Image/index.tsx
=> COM-3859: hide loader if error on media url

src/core/data/constants.ts, src/screens/courses/list/TrainerCourses/index.tsx, src/screens/courses/list/helper.ts
=> COM-3852: optimize course status

src/screens/courses/cardTemplates/FlashCard/index.tsx
=> COM-3860: fix flashcard

src/screens/courses/cardTemplates/FlashCard/index.tsx
=> MEP OPTA 03/12/24

app.config.js, src/components/form/Button/index.tsx, src/components/form/SecondaryButton/index.tsx, src/core/data/constants.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/AdminCourseProfile/styles.ts, src/types/AttendanceSheetTypes.ts
=> COM-3848: display single courses attendance sheets

app.config.js, eas.json
=> update version 2.30.0

src/screens/explore/BlendedAbout/index.tsx
=> COM-3868 - remove useless median dot + fix error when no trainers

src/components/AttendanceSignatureContainer/index.tsx, src/components/AttendanceSignatureContainer/styles.ts
=> COM-3854: bigger canva on web mobile

src/core/data/constants.ts, src/core/data/tabs.ts, src/core/helpers/notifications.ts, src/navigation/AppNavigation/index.tsx, src/screens/courses/profile/HandleAttendanceSheetNotification/index.tsx, src/screens/courses/profile/UpdateAttendanceSheet/index.tsx, src/types/NavigationType.ts
=> COM-3855: receive notification

src/components/About/index.tsx, src/components/About/styles.ts, src/components/TrainerCell/index.tsx, src/components/TrainerCell/style.ts, src/components/UploadMethods/index.tsx, src/components/learnerPendingActions/AttendanceSheetCell/index.tsx, src/core/helpers/utils.ts, src/screens/courses/profile/CreateAttendanceSheet/index.tsx, src/screens/courses/profile/HandleAttendanceSheetNotification/index.tsx, src/screens/courses/profile/LearnerCourseProfile/index.tsx, src/screens/courses/profile/UpdateAttendanceSheet/index.tsx, src/screens/explore/BlendedAbout/index.tsx, src/screens/explore/BlendedAbout/styles.ts, src/styles/common.ts, src/types/AttendanceSheetTypes.ts, src/types/CourseTypes.tsx, src/types/NavigationType.ts
=> Feature trainers

src/api/questionnaires.ts, src/components/QuestionnaireQRCodeCell/index.tsx, src/core/data/constants.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx
=> COM-3877 - display qrcode and questionnaireForm at every courseTimeline

app.config.js, eas.json
=> update version 2.31.0

__tests__/authentication.test.js, src/api/courses.ts, src/screens/courses/list/LearnerCourses/index.tsx, src/screens/courses/list/TrainerCourses/index.tsx, src/screens/profile/Profile/index.tsx, src/types/AxiosTypes.ts, src/types/CourseTypes.tsx
=> COM-3882: display tutor courses

app.config.js, eas.json
=> update version 2.32.0

app.config.js
=> update version 2.32.0.1

app.config.js, eas.json
=> MEP 13/02/2025

.eslintrc.js, src/screens/courses/profile/CreateAttendanceSheet/index.tsx
=> COM-3927: fix bug

.eslintrc.js, src/screens/courses/list/TrainerCourses/index.tsx, src/screens/courses/profile/CreateAttendanceSheet/index.tsx
=> MEP 20/02/2025

src/components/CalendarIcon/index.tsx, src/components/CalendarIcon/styles.ts, src/components/UploadMethods/index.tsx, src/components/steps/LiveCell/index.tsx, src/components/steps/LiveCellInfoModal/index.tsx, src/core/data/constants.ts, src/core/helpers/dates/companiDates.ts, src/screens/courses/list/helper.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/LearnerCourseProfile/index.tsx, src/screens/courses/profile/SubProgramProfile/index.tsx, src/screens/courses/profile/TrainerCourseProfile/index.tsx, src/screens/courses/profile/helper.tsx, src/screens/explore/BlendedAbout/index.tsx, src/types/StepTypes.tsx
=> COM-3944: optimize dates

src/components/UploadMethods/index.tsx, src/core/data/constants.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/CreateAttendanceSheet/index.tsx
=> COM-3926: adapt attendance sheets upload to single courses

__tests__/authentication.test.js, src/screens/courses/list/LearnerCourses/index.tsx, src/screens/courses/list/TrainerCourses/index.tsx, src/screens/courses/list/helper.ts, src/screens/profile/Profile/index.tsx, src/types/AxiosTypes.ts, src/types/StepTypes.tsx
=> COM-3947: have next steps for every course

app.config.js, src/core/data/constants.ts, src/screens/courses/profile/LearnerCourseProfile/index.tsx
=> COM-3937: can sign attendance as trainee

src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/LearnerCourseProfile/index.tsx
=> COM-3960: hide useless sections

app.config.js, src/components/UploadMethods/index.tsx, src/core/data/constants.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/CreateAttendanceSheet/index.tsx, src/screens/courses/profile/LearnerCourseProfile/index.tsx
=> fusion de branche Feature single

app.config.js, eas.json
=> update version 2.33.0

app.config.js, eas.json
=> update version 2.34.0

src/api/courses.ts, src/components/cards/ProgressBar/styles.ts, src/navigation/AppNavigation/index.tsx, src/screens/courses/TraineeFollowUp/index.tsx, src/screens/courses/TraineeFollowUp/styles.ts, src/screens/courses/profile/LearnerCourseProfile/index.tsx, src/screens/courses/profile/styles.ts, src/types/AxiosTypes.ts, src/types/NavigationType.ts
=> COM-4012: display trainee progress

src/components/ELearningCell/styles.ts, src/components/cards/FillTheGapPropositionList/index.tsx, src/screens/courses/cardTemplates/FillTheGapCard/index.tsx
=> COM-4029: fix bug

src/screens/courses/cardTemplates/FillTheGapCard/index.tsx, src/screens/courses/cardTemplates/FillTheGapCard/styles.ts
=> COM-4029: fix display

src/components/learnerPendingActions/AttendanceSheetCell/index.tsx, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/HandleAttendanceSheetNotification/index.tsx, src/screens/courses/profile/LearnerCourseProfile/index.tsx, src/types/AttendanceSheetTypes.ts
=> COM-4019: refacto signatures

src/components/AttendanceEndScreen/index.tsx, src/components/AttendanceSheetSelectionForm/index.tsx, src/components/UploadMethods/index.tsx, src/components/form/Button/index.tsx, src/components/form/MultipleCheckboxList/index.tsx, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/CreateAttendanceSheet/index.tsx
=> COM-4025: can sign inter course

src/screens/courses/profile/AdminCourseProfile/index.tsx
=> COM-4037: don't show future slots

src/components/AttendanceEndScreen/index.tsx, src/components/AttendanceSheetSelectionForm/index.tsx, src/components/AttendanceSheetSummary/index.tsx, src/components/UploadMethods/index.tsx, src/components/form/MultipleCheckboxList/index.tsx, src/core/data/constants.ts, src/core/helpers/utils.ts, src/screens/courses/profile/AdminCourseProfile/index.tsx, src/screens/courses/profile/CreateAttendanceSheet/index.tsx, src/screens/courses/profile/LearnerCourseProfile/index.tsx, src/screens/courses/profile/UpdateAttendanceSheet/index.tsx, src/types/NavigationType.ts
=> COM-4036: can sign attendance sheet for intra as trainer

src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx, src/types/CardType.tsx
=> COM-4048: display accurate text
