.eslintrc.js
package-lock.json
package.json
src/components/form/Input.jsx

Finalement j'ai tout mis dans un ticket parce qu'il n'y a pas beaucoup de changements
pour le eslint: on a des warning sur les useEffect qui ont pour deuxieme argument mais j'ai l'impression que c'est normal (cf la remarque de ce paragraphe https://fr.reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects )
pour ce qui est des bonnes pratiques du state (cf article). 
- pour le premier point: on n'en a pas 
- pour le deuxieme point: je n'ai vu que showPassword, je l'ai donc changé
- pour le troisieme point: j'ai l'impression qu'on a ce cas dans sendEmail (forgotPassword) mais on ne peut pas utiliser de useEffect a l'interieur d'une fonction. J'ai cherché mais je n'ai pas trouve la bonne pratique dans notre cas. Comme la suite du code ne depend pas vraiment du …

COM-1390 add eslint for hooks + fix the use of a state

---

package.json

Permet de lancer les 2 commandes peut importe le résultat de la 1ère. Sans ça, si ts ne passe pas, le test lint n'est pas lancé

Fix gitflow

---

src/components/cards/QuestionCardFooter.tsx
src/components/cards/SurveyScoreSelector.tsx
src/components/form/Button.tsx
src/screens/courses/cardTemplates/CardTemplate.tsx
src/screens/courses/cardTemplates/SingleChoiceQuestionCard.tsx
src/screens/courses/cardTemplates/SurveyCard.tsx
src/types/CardType.tsx

Je peux voir une carte sondage et le résultat de l'utilisateur est stocké dans une variable. Le bouton pour passer à la carte suivante est bloqué tant que l'utilisateur n'a pas sélectionné de carte.
Refacto du NiButton et de QuestionCardFooter

Com 1466 2 - Survey Card

---

src/components/cards/AnswerTextArea.tsx
src/components/cards/CardFooter.tsx
src/components/cards/QuestionCardFooter.tsx
src/components/cards/QuizProposition.tsx
src/components/style/FooterGradient.tsx
src/screens/courses/cardTemplates/FlashCard.tsx
src/screens/courses/cardTemplates/MultipleChoiceQuestionCard.tsx
src/screens/courses/cardTemplates/OpenQuestion.tsx
src/screens/courses/cardTemplates/SingleChoiceQuestionCard.tsx
src/screens/courses/cardTemplates/TextMediaCard.tsx
src/screens/courses/cardTemplates/TitleTextCard.tsx
src/screens/courses/cardTemplates/TitleTextMediaCard.tsx
src/styles/cards.ts
src/styles/colors.ts
src/styles/metrics.ts

gradient sur qcu et qcm pour sous-entendre qu'il faut scroller
lorsque l'explication apparait sur qcu et qcm, les réponses ne montent plus et passent sous l'explication (vu avec Romain)
marginTop n'a rien à faire dans les footer (questioncardfooter et cardfooter), je l'ai retiré et ajouté un marginBottom sur les cartes (vérifier que le margin est présent sur les différentes cartes (qcu, qcm, titletext, titlemedia, titletextmedia, sondage, flashcard, open question)

Com 1434-2 + REFACTO

---

app.json

- Cas d'usage : Il fallait ajouter `permissions: []` dans app.json pour demander le moins de permissions possibles a l'utilisateur. Par defaut on en demandait 50 (dont la localisation par exemple). Maintenant c'est descendu a 22.

change permission

---

src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/index.tsx
src/screens/courses/cardTemplates/MultipleChoiceQuestionCard/styles.ts
src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
src/screens/courses/cardTemplates/OrderTheSequenceCard/styles.ts
src/styles/cards.ts

retour de Romain, le gradient est quasiment invisible sur Mettre dans l'ordre, je l'ai déplacé dans draggableContainer qui est en fait le véritable container du composant (on garde container pour éviter un comportement pas souhaitable au drag (en gros la bull qu'on drag grossit et c'est moche donc on garde container pour y mettre le margin et empêcher ça))
mettre un texte explicatif au dessus du drag n drop

COM-1521-gradient: fix gradient

---

src/components/cards/ProgressBar/index.tsx
src/components/cards/ProgressBar/styles.ts

Cas d'usage :
on retire le décompte des cartes (ex: 3/5) à côté de la progress bar

COM-1522-REFACTO: delete text progression

---

app.json
src/components/CalendarIcon/index.tsx

- Cas d'usage : L'icone calendrier prend la forme multi-date uniquement si il y a plusieurs dates (et non pas plusieurs creneaux), le nombre qui s'affiche est le nombre de date. La progression prend toujours en compte le nombre de creneau.

COM-1599 counting dates except for progress for calendaricon

---

src/screens/explore/About/index.tsx

- Cas d'usage : quand on est sur "À propos" et qu'on quitte explore (en s'inscrivant/lançant une activité ou en switchant d'onglet) et qu'on revient dessus, on est focus sur le "Catalogue des formations e-learning" et non "À propos"

COM-1615-navigation: focus on catalog when leave explore and come back

---

src/components/CalendarIcon/index.tsx

dans prochains rendez-vous, si j'ai des créneaux sur un seul jour, le chiffre 1 n'apparait pas

COM-1599-fix-date-when-1-day: fix

---

src/AppContainer/index.tsx
src/screens/explore/About/index.tsx

quand je reviens sur explorer après mettre inscrit à une activité ou avoir lancé une activité, j'arrive sur le catalogue et non sur à propos.

COM-1615: catalog is the default page for explore wherever we come from

---

src/components/cards/FillTheGapProposition/styles.ts
src/components/cards/FillTheGapQuestion/index.tsx
src/styles/metrics.ts

quand le texte d'une proposition de Fill The Gap fait 14 ou 15 caractères, elle déborde sur Android. 
Fixé en agrandissant le container (ne respecte pas la base 8 mais vu avec Romain)

COM-1649: fix overflow

---

src/AppContainer/index.tsx
src/screens/courses/CourseList/index.tsx
src/store/main/actions.ts
src/store/main/reducers.ts
src/store/main/selectors.ts
src/types/store/MainStoreType.ts

- Cas d'usage : Refacto de `userRole` pour le mettre dans loggedUser et et non a cote pour qu'il soit enregistré en meme temps

COM-1669 - update role in redux

---

src/screens/explore/About/index.tsx

quand je lance une activité depuis à propos ou que je la quitte* je n'ai pas de "flash" furtifs des screens intermédiaires
(à vérifier que ça marche quand on s'inscrit à une formation et pas seulement quand on en continue une)
*quitter = flèche retour sur la startcard, crois sur les autres cartes, finir l'activité ou flèche back native sur android)

Com 1615 navigation3

---

src/components/cards/FillTheGapQuestion/index.tsx

Si les mots sont collés aux balises <trou> dans le texte a trou, on voit un gap et non pas <trou>
Pour tester vous pouvez regarder communication empathique/reporter un echange/ professionnel du prendre soin.

COM-1687 fix <trou> displaying instead of gap

---

src/api/authentication.ts
src/api/users.ts
src/context/AuthContext.ts

- Cas d'usage : Ajout de `origin` dans le payload de la creation d'un utilisateur

COM-1710 - add origin in user creation

---

src/components/CreateAccountForm/index.tsx
src/components/form/Input/index.tsx
src/screens/CreateAccount/index.tsx
src/screens/EmailForm/index.tsx

désactivation des inputs (textinput, bouton de retour arrière / bouton croix et backhandler quand on attend un retour du back)
prise en compte du commentaire de Romain sur le ticket COM-1701 : "sur la page EmailForm ne pas mettre le bouton en inactif et gris. Il faut que ce bouton soit actif, et quand l’utilisateur clique dessus alors que le champ renseigné ne respecte pas les contraintes, le message d’erreur apparaît (comme c’est le cas dans le process de création de compte, pour le Nom par exemple)"

COM-1653: desactiver modification quand retour du back en attente

---

app.json

j'ai recu ce message d'apple
```
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
We noticed that your app requests the user’s consent to access the camera, but doesn’t sufficiently explain the use of the camera in the purpose string.
To help users make informed decisions about how their data is used, all permission request alerts need to specify how your app will use the requested information.
Next Steps
Please revise the relevant purpose string in your app’s Info.plist file to specify why your app needs access to the user’s camera. Make sure the purpose string includes an example of how the user’s data will be used.
You can modify your app's Info.plist file using the property list editor in Xcode.
Resources
- See examples of helpful, informative purpose …
```

COM-1777 - update message to access camera

---

app.json

- Cas d'usage : Pour le store android, il faut ajouter les permissions dont on a besoin: ici camera et media library. 
https://docs.expo.io/distribution/app-stores/#android-permissions
https://docs.expo.io/versions/latest/sdk/camera/#configuration
https://docs.expo.io/versions/latest/sdk/imagepicker/#configuration

add permission for camera

---

src/components/cards/QuizCardFooter/index.tsx
src/styles/cards.ts

retirer la position absolue de l’explanation dans QuizCardFooter pour qu'elle ne cache pas les réponses au quizz

COM-1764: remove absolute position

---

src/components/ELearningCell/index.tsx
src/screens/courses/CourseProfile/index.tsx
src/screens/courses/cardTemplates/EndCard/index.tsx

quand on termine une activité depuis le catalogue on arrive sur courseprofile avec l'étape correspondante à l'activité déjà ouverte

COM-1761: open step when activity end

---

src/screens/profile/PasswordEdition/index.tsx
src/screens/profile/ProfileEdition/index.tsx

Harmonisation de l'UX entre la modification d'infos/mot de passe et la création de compte : plus de bouton disabled et message d'erreur seulement quand on a cliqué sur "valider"

COM-1768: ux/ui adaptation

---

src/components/UpdateAppModal/index.tsx

- Cas d'usage : Sur iphone, quand on me demande de mettre l'application a jour, je suis redirigée vers la bonne app dans l'app store

COM-1820 - fix link to update on ios

---

src/components/ForgotPasswordModal/index.tsx
src/screens/EmailForm/index.tsx

- Cas d'usage : plus de warning d'erreur quand on quitte la modale forgot password (erreur visiblement dû au listener sur les input texte avec Keyboard.addListener. Il semble que l'erreur popait car on n'appelait pas la une même fonction au mount et au unmount mais un set State et il vaut mieux utiliser cela sous forme de fonction unique qu'on monte et démonte)
+ petit changement dans la logique du setErrormessage
(fait en PP avec Chloé, donc pas besoin qu'elle relise, tu pourras merger directement après validation @sophiemoustard)

Com 1815 2

---

src/components/InternalRulesModal/index.tsx
src/components/InternalRulesModal/styles.ts
src/styles/colors.ts

changement de l'opacité de la couleur de fond derrière les modales + ajout d'une marge à la fin du règlement pour ne pas que le dégradé empiète dessus (réduction de la taille du dégradé qui était plus grand que nécessaire et obligeait à mettre une marge énorme)

COM-1811: change bg color and add margin

---

src/styles/common.ts

- Cas d'usage : Si il y a un lien dans une carte `[texte a afficher](lien)` il est en rose

COM-1871 add style for link

---

.gitignore
App.tsx
app.json
package-lock.json
package.json

**Cas d'usage** : 
Mise en place de sentry sur l'app (https://sentry.io/organizations/alenvi/issues/?project=5606219)
**Ce qui a été fait** :
cf https://docs.expo.io/guides/using-sentry/
- Sentry est initialisé dans App.tsx
- La config sentry a été ajouté dans app.json
**Ce qui a été changé** : 
- afin de ne pas inscrire directement la clef authKey dans app.json (comme fait dans le tuto), nous avons choisi de la passer dans un fichier shell qui sera exécuté au démarrage.  (ce n'est plus fait - cf UPDATE)
**Ce qu'il reste à faire** : 
- Supprimer sentry en local, désactiver enableInExpoDevelopment
**Comment tester** : 
- Ajouter la clef sentryKey dans vos env.local/dev/prod
- Ajouter le fichier shell dans votre dossier racine (~) nommé setSentryAuthKey.sh (ne plus le faire cf UPDATE)
- …

COM-1858 - Add sentry

---

src/screens/courses/CourseList/index.tsx

- [] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
master en api)
- Non parce que l'appel au back renvoie une 403, c'est pas forcément un problème mais je sais pas si on peut dire que c'est full compatible pour autant
-~~ J'ai ajouté une variable d'environnement :~~
- Cas d'usage : en tant que testeur j'ai accès dans mes formations aux programmes pour lesquels je suis défini comme testeur. 
Tester le cas où je me connecte en ROF/admin-vendeur (j'ai accès à tous les …

COM-1957 : show draft program section for testers

---

src/components/ZoomImage/index.tsx
src/components/activities/ActivityCell/index.tsx
src/components/cards/Video/index.tsx

master en api)
- Oui parce que je ne fais que des changements mineurs qui n'impactent pas les routes
- Cas d'usage : passage des let en useRef. Je n'ai finalement pas changé le let dans FlashCard car étant donné que les cartes sont conservés quand on switche de carte, avec un useRef, la valeur de rotationValue le serait aussi or on veut qu'elle soit réinitialisée à chaque fois qu'on revient sur la carte donc il faut utiliser un let plutôt qu'un useRef.
- TEST : 
- quand je fais …

COM-2198: replace let with useRef

---

.github/pull_request_template.md

Nouveau template de PR pour suivre les changement de la PR #392 et le commentaire de Chloé : "Ca me fait penser @sophie M il faudrait peut etre mettre un message sur le slite pour qu'a la prochaine mep, avant de lancer le build, la personne qui le lance verifie que son env.prod est bien a jour + lors de la mise dans les stores il faut changer le mail/mdp pour apple".
Qu'en pensez-vous ?

Change PR template for env.staging

---

package-lock.json
package.json

MIS À JOUR AUTOMATIQUEMENT
@types/react 17.0.19 => 16.9.35 => downgrade par Expo Update
@types/react-dom 17.0.9 => 16.9.8 => downgrade par Expo Update
@types/react-native 0.64.13 => 0.63.2 => downgrade par Expo Update
MIS À JOUR MANUELLEMENT
typescript 4.4.2 => 4.4.3
Fix issues
https://github.com/microsoft/TypeScript/releases
@babel/core 7.15.0 => 7.15.5
bug fixes and performances
https://github.com/babel/babel/blob/main/CHANGELOG.md
PAS MIS À JOUR
@react-navigation/native/@react-navigation/stack/@react-navigation/bottom-tabs/@react-navigation/material-top-tabs => casse l'appli et TS-LINT => ticket spécifique pour le passage à React Navigation 6 à venir
@types/luxon 1.27.1 => 2.0.2 => casse TS-LINT (problème de typage) => ticket spécifique à venir
react-redux 7.2.2 => 7.2.4 => toujours le …

COM-2349: npm update

---

src/components/cards/QuizCardFooter/index.tsx
src/screens/courses/cardTemplates/SingleChoiceQuestionCard/index.tsx

master en api)
- Oui parce que le changement n'est qu'au niveau de l'UI
- Cas d'usage : sur les cartes QCU je n'ai plus le bouton "Valider" car il ne sert à rien étant donné qu'on n'a pas à cliquer dessus pour valider notre choix

COM-2336: remove validation button on single choice question

---

src/components/CourseProfileStickyHeader/index.tsx
src/components/CourseProfileStickyHeader/styles.ts
src/screens/courses/CourseProfile/index.tsx

master en api)
- Oui parce que changement cosmétique
- Cas d'usage : mini changement demandé par Romain => sur le sticky header on a un pourcentage plutôt qu'un ratio

COM-2340: percentage rather than ratio

---

.github/workflows/integration-tests.yml
.github/workflows/lint.yml
package-lock.json

Node Js 14.16.0 => 14.18.0
Pré-requis
nvm install 14.18.0 (si pas déjà fait)
nvm use 14.18.0 sur compani-formation (penser à le changer dans la config iTerm si besoin)
npm install -g expo-cli (si pas déjà fait)
rm -rf node_modules && rm package-lock.json && npm i

[ne pas fusionner] COM-2344: update node js

---

src/components/CalendarIcon/index.tsx
src/core/helpers/dates.ts
src/screens/explore/BlendedAbout/index.tsx

master en api)
- Oui parce que traitement front uniquement
-~~ J'ai ajouté une variable d'environnement :~~
- Cas d'usage : fix du bug de léa : sur les calendar icon et le à propos des formations le jour n'était pas le bon : on avait dimanche 22 novembre au lieu de lundi 22 novembre sur la formation Accueil par exemple

COM-2538: fix day bug

---

src/api/programs.ts
src/core/data/constants.ts
src/core/helpers/notifications.ts

master en api)
- Si j'en envoie un nouveau, explication et gestion de la compatibilite: le paramètre n'est pas obligatoire
- Cas d'usage : quand une nouvelle formation elearning est publiée, je reçois une notification qui me renvoie vers le à propos de cette formation
⚠️ je n'ai pas testé sur iPhone ⚠️

COM-2516: open notification for new course

---

src/components/ELearningCell/index.tsx
src/components/steps/LiveCell/index.tsx
src/components/steps/NextStepCell/index.tsx
src/core/helpers/utils.ts
src/screens/courses/CourseList/index.tsx
src/screens/courses/CourseProfile/index.tsx
src/screens/profile/Profile/index.tsx
src/types/StepTypes.tsx

master en api)
- Non parce que on utilise progress.live / progress.eLearning / progress.blended qui sont définis dans le nouveau back
- Cas d'usage : la progression s'affiche correctement
TEST : pull dev et comparer qu'on a bien la même progression sur l'appli dev et sur cette branche : 
- créneaux à venir
- progression sur une formation 100% présentielle (pie chart sur la liste des formations + barre sur le profil de la formation)
- progression sur une formation 100 % elearning (pie chart sur la liste des formations + barre sur le profil de la formation)
- progression sur une formation mixte (pie chart sur la liste des formations + barre sur le profil …

COM-2614: refacto progress

---

src/components/ELearningCell/index.tsx
src/components/steps/StepCellTitle/index.tsx
src/core/helpers/utils.ts
src/types/StepTypes.tsx

---
---
- Périmètre interfaces / rôles : app-formation / tous
- Cas d'usage : je peux voir la durée d'une étape elearning + boyscout je peux de nouveau accéder aux formations en brouillon (bug en prod)
- Comment tester ? : 
- aller sur une formation elearning ou mixte : la durée des étapes (si elle est définie) est affichée

COM-2721: display theoretical duration for steps

---

src/core/helpers/utils.ts

---
---
- Périmètre interfaces / rôles : apprenant.e
- nettoyage de la memoire apres un jingle. 
- Je n'ai pas reussi a reproduire le pb sur simu ios. (je n'ai pas testé avec un iphone physique)
- de la doc expo : https://docs.expo.dev/versions/v43.0.0/sdk/av/#playback-api
- un commentaire interessant sur github https://github.com/expo/expo/issues/1873#issuecomment-488912452
- avec android
- sur la branche dev : activer une quinzaine de fois le jingle (faire une activité quiz 2-3 fois de suite)  jusqu'a se que le son ne soit plus emis. L'erreur `[Unhandled promise rejection: Error: h.f.c.d.j0.n$b: AudioTrack init failed: 0, Config(44100, 12, 44100)]` s'affiche egalement sur la console.
- revenir sur cette branche COm-2768, repeter l'operation. Le son …

COM-2768 unload audio after usage

---

src/screens/courses/CourseProfile/index.tsx
src/types/CourseTypes.tsx

---
---
- Périmètre interfaces / rôles : mobile / vendeur  tous/rof/admin
- Cas d'usage : je ne vois le bouton de téléchargement que si le dernier créneau a été émargé pour un stagiaire
- côté mobile :
- sur le profil : le nombre de formation s'affiche bien
- sur la liste des formation : tout s'affiche bien  
- sur une formation elearning : je ne vois pas le bouton de téléchargement
- sur une formation mixte en cours ou sans émargement sur le dernier créneau : je ne vois pas le bouton de téléchargement
- sur une formation mixte dont le dernier créneau a été émargé (peu importe que ça soit le stagiaire concerné ou non) : je vois le bouton de téléchargement d'attestation
- côté vendeur :  sur la liste des formations sur le profil d'un stagiaire tout s'affiche …

COM-2758: display download button

---

src/screens/courses/CourseProfile/index.tsx

---
---
- Périmètre interfaces / rôles : vendeur/client/mobile rof/coach/admin
- Cas d'usage : changement des noms des fichiers téléchargés suivants : convocation, feuilles d’emargement, attestation de fin de formation, facture, avoir
- télécharger les docs suivants : 
- convocation : convocation_nom de la formation (struct - nom programme - misc) (intra et inter)
- feuilles d’emargement : feuilles d’emargement_nom de la formation (struct - nom programme - misc) (intra et inter)
- attestation de fin de formation : attestation_nom de la formation (struct - nom programme - misc) (intra et inter) + mobile
- facture : payeur - numero facture (ex : Onela-FACT-00023)
- avoir :  payeur - numero avoir (ex : Onela-AV-00023)
_Si tu as lu cette description, pense a réagir avec …

COM-2879: change pdf name for completion certificate

---

src/screens/courses/cardTemplates/OrderTheSequenceCard/index.tsx
src/screens/courses/cardTemplates/OrderTheSequenceCard/styles.ts

---
---
- Périmètre interfaces / rôles : mobile-formation / tous
- Cas d'usage : sur les cartes mettre dans l'ordre quand les propositions sont très longue je peux scroller
⚠️ en utilisant NestableScrollContainer, NestableDraggableFlatList je n'arrive plus à avoir les proposition alignées en bas de l'écran comme c'était le cas avant, le space-between ne semble pas fonctionner, si vous avez une solution je suis preneur
- tester des cartes mettre dans l'ordre avec des propositions courtes (scroll non nécessaire) et longues (scroll nécessaire) 

COM-2929: can scroll big flatlist

---

src/components/steps/LiveCell/index.tsx
src/screens/courses/CourseProfile/index.tsx

---
---
- Périmètre interfaces / rôles : mobile-formation utilisateur
- la progression d'une l'étape présentielle/distancielle sur l'app mobile correspond bien à son avancement dans le temps uniquement 
- quand je clique sur une cellule d'étape présentielle ou distancielle ça m'affiche le détail des créneaux

COM-2983: can't show activity on non-elearning step

---

src/core/helpers/utils.ts
src/screens/courses/profile/TrainerCourseProfile/index.tsx

---
---
- Périmètre interfaces / rôles : formateur
- Cas d'usage :
- suite a la vigilance de Manon et la confirmation de Romain, on a repassé ce ticket en PR pour deux raisons:
- la plice du bouton "Espace admin' etait trop claire  
- il y avait un espace avant les noms des stagiaires sur la liste
- sur l'espace intervenant, sur la page trainerCourseProfil, le texte du bouton "Espace Admin" est en GREY[700] (plus sombre que celui de "a propos")
- sur l'ecran "espace Admin", sur la liste des stagiaire, le nom des stagiaire est aligné avec l'email

Com 2977 2

---

.github/workflows/integration-tests.yml
.github/workflows/ts-lint.yml

Mise à jour des library actions/checkout et actions/setup-node car les actions utilisant node12 est bientot déprécié.

COM-3371 update libraries for github actions
